# Description: This playbook installs the Zabbix agent on a remote host and adds it to the Zabbix server. It also sends an email notification in case of success or failure.
# Command to run the playbook: ansible-playbook -i /path/to/your/hosts.ini zabbix/main.yml

- name: Install Zabbix agent
  hosts: your_vm_host
  become: true
  vars:
    vars_file: vars.yml
    
  tasks:
    - name: Install Zabbix agent package
      block:
        - name: Add Zabbix repository (Debian)
          apt_repository:
            repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu $(lsb_release -sc) main"
            state: present
          when: ansible_os_family == "Debian"

        - name: Add Zabbix repository (RedHat)
          yum_repository:
            name: zabbix
            description: Zabbix Official Repository
            baseurl: "http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/$releasever/$basearch/"
            gpgcheck: no
            enabled: yes
          when: ansible_os_family == "RedHat"

        - name: Install Zabbix agent package (Debian)
          apt:
            name: zabbix-agent
            state: present
          when: ansible_os_family == "Debian"

        - name: Install Zabbix agent package (RedHat)
          yum:
            name: zabbix-agent
            state: present
          when: ansible_os_family == "RedHat"
      rescue:
        - name: Print error message
          debug:
            msg: "An error occurred during Zabbix agent installation."

    - name: Configure Zabbix agent
      template:
        src: zabbix_agent.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: 0644
      notify: restart zabbix agent

    - name: Add host to Zabbix server
      zabbix_host:
        server_url: "{{ zabbix_server_url }}"
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        host_name: "{{ zabbix_host_name }}"
        visible_name: "{{ zabbix_visible_name }}"
        groups:
          - name: your_host_group
        templates:
          - name: your_template_name
      notify: Restart Zabbix server

    - name: mail Notification
      block:
        - name: Send success email
          mail:
            host: your_smtp_server
            port: your_smtp_port
            username: your_smtp_username
            password: your_smtp_password
            to: Your Name <your.email@example.com>
            subject: Zabbix agent installation successful
            body: "The Zabbix agent was successfully installed and added to the Zabbix server. The IP address of the host is: \"{{ ansible_host }}\""
          when: not ansible_failed_task
          delegate_to: localhost

        - name: Send failure email
          mail:
            host: your_smtp_server
            port: your_smtp_port
            username: your_smtp_username
            password: your_smtp_password
            to: Your Name <your.email@example.com>
            subject: Zabbix agent installation failed
            body: "An error occurred during the Zabbix agent installation on host with IP: \"{{ ansible_host }}\". The error was: \"{{ ansible_failed_result }}\""
          when: ansible_failed_task is defined
          delegate_to: localhost

  handlers:
    - name: restart zabbix agent
      service:
        name: zabbix-agent
        state: restarted

    - name: Restart Zabbix server
      service:
        name: zabbix-server
        state: restarted      