---
- name: Setup MongoDB
  hosts: your_target_hosts
  gather_facts: yes
  become: true

  vars:
    mongodb_version: "4.0"  # Default MongoDB version

  tasks:
    - name: Check OS version
      setup:
      register: os_info


    - include: ubuntu_mongodb_setup.yml
      when: "'Ubuntu' in os_info.ansible_facts['ansible_distribution']"

    - include: rhel_mongodb_setup.yml
      when: "'RedHat' in os_info.ansible_facts['ansible_distribution'] or 'CentOS' in os_info.ansible_facts['ansible_distribution']"
