---
#Ansible playbook for Docker installation on Ubuntu 

- name: Install Docker on Ubuntu
  hosts: localhost
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - include_tasks : ubuntu_setup.yaml 
      when: ansible_os_family=="Ubuntu"
    - include_tasks : rhel_setup.yaml 
      when: ansible_os_family=="RedHat"
    